# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/pos_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/pos_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/pos_service.proto\x12\x03pos\",\n\x16GetProductPriceRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"[\n\x17GetProductPriceResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0f\n\x07message\x18\x04 \x01(\t\"B\n\x19UpdateProductPriceRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x11\n\tnew_price\x18\x02 \x01(\x02\">\n\x1aUpdateProductPriceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x11\x42uyProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"M\n\x12\x42uyProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rquantity_sold\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\";\n\x13RequestStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"1\n\x14RequestStockResponse\x12\x19\n\x11quantity_provided\x18\x01 \x01(\x05\x32\x8b\x03\n\x03POS\x12L\n\x0fGetProductPrice\x12\x1b.pos.GetProductPriceRequest\x1a\x1c.pos.GetProductPriceResponse\x12U\n\x12UpdateProductPrice\x12\x1e.pos.UpdateProductPriceRequest\x1a\x1f.pos.UpdateProductPriceResponse\x12[\n\x18NotifyPeersToUpdatePrice\x12\x1e.pos.UpdateProductPriceRequest\x1a\x1f.pos.UpdateProductPriceResponse\x12=\n\nBuyProduct\x12\x16.pos.BuyProductRequest\x1a\x17.pos.BuyProductResponse\x12\x43\n\x0cRequestStock\x12\x18.pos.RequestStockRequest\x1a\x19.pos.RequestStockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pos_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTPRICEREQUEST']._serialized_start=32
  _globals['_GETPRODUCTPRICEREQUEST']._serialized_end=76
  _globals['_GETPRODUCTPRICERESPONSE']._serialized_start=78
  _globals['_GETPRODUCTPRICERESPONSE']._serialized_end=169
  _globals['_UPDATEPRODUCTPRICEREQUEST']._serialized_start=171
  _globals['_UPDATEPRODUCTPRICEREQUEST']._serialized_end=237
  _globals['_UPDATEPRODUCTPRICERESPONSE']._serialized_start=239
  _globals['_UPDATEPRODUCTPRICERESPONSE']._serialized_end=301
  _globals['_BUYPRODUCTREQUEST']._serialized_start=303
  _globals['_BUYPRODUCTREQUEST']._serialized_end=360
  _globals['_BUYPRODUCTRESPONSE']._serialized_start=362
  _globals['_BUYPRODUCTRESPONSE']._serialized_end=439
  _globals['_REQUESTSTOCKREQUEST']._serialized_start=441
  _globals['_REQUESTSTOCKREQUEST']._serialized_end=500
  _globals['_REQUESTSTOCKRESPONSE']._serialized_start=502
  _globals['_REQUESTSTOCKRESPONSE']._serialized_end=551
  _globals['_POS']._serialized_start=554
  _globals['_POS']._serialized_end=949
# @@protoc_insertion_point(module_scope)
