# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import pos_service_pb2 as proto_dot_pos__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/pos_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class POSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductPrice = channel.unary_unary(
                '/pos.POS/GetProductPrice',
                request_serializer=proto_dot_pos__service__pb2.GetProductPriceRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.GetProductPriceResponse.FromString,
                _registered_method=True)
        self.UpdateProductPrice = channel.unary_unary(
                '/pos.POS/UpdateProductPrice',
                request_serializer=proto_dot_pos__service__pb2.UpdateProductPriceRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.UpdateProductPriceResponse.FromString,
                _registered_method=True)
        self.NotifyPeersToUpdatePrice = channel.unary_unary(
                '/pos.POS/NotifyPeersToUpdatePrice',
                request_serializer=proto_dot_pos__service__pb2.UpdateProductPriceRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.UpdateProductPriceResponse.FromString,
                _registered_method=True)
        self.BuyProduct = channel.unary_unary(
                '/pos.POS/BuyProduct',
                request_serializer=proto_dot_pos__service__pb2.BuyProductRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.BuyProductResponse.FromString,
                _registered_method=True)
        self.RequestStock = channel.unary_unary(
                '/pos.POS/RequestStock',
                request_serializer=proto_dot_pos__service__pb2.RequestStockRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.RequestStockResponse.FromString,
                _registered_method=True)
        self.PrepareUpdatePrice = channel.unary_unary(
                '/pos.POS/PrepareUpdatePrice',
                request_serializer=proto_dot_pos__service__pb2.PrepareUpdatePriceRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.PrepareUpdatePriceResponse.FromString,
                _registered_method=True)
        self.CommitUpdatePrice = channel.unary_unary(
                '/pos.POS/CommitUpdatePrice',
                request_serializer=proto_dot_pos__service__pb2.CommitUpdatePriceRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.CommitUpdatePriceResponse.FromString,
                _registered_method=True)
        self.AbortUpdatePrice = channel.unary_unary(
                '/pos.POS/AbortUpdatePrice',
                request_serializer=proto_dot_pos__service__pb2.AbortUpdatePriceRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.AbortUpdatePriceResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/pos.POS/SendHeartbeat',
                request_serializer=proto_dot_pos__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_pos__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class POSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProductPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyPeersToUpdatePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareUpdatePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitUpdatePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortUpdatePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_POSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductPrice,
                    request_deserializer=proto_dot_pos__service__pb2.GetProductPriceRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.GetProductPriceResponse.SerializeToString,
            ),
            'UpdateProductPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProductPrice,
                    request_deserializer=proto_dot_pos__service__pb2.UpdateProductPriceRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.UpdateProductPriceResponse.SerializeToString,
            ),
            'NotifyPeersToUpdatePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyPeersToUpdatePrice,
                    request_deserializer=proto_dot_pos__service__pb2.UpdateProductPriceRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.UpdateProductPriceResponse.SerializeToString,
            ),
            'BuyProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyProduct,
                    request_deserializer=proto_dot_pos__service__pb2.BuyProductRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.BuyProductResponse.SerializeToString,
            ),
            'RequestStock': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestStock,
                    request_deserializer=proto_dot_pos__service__pb2.RequestStockRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.RequestStockResponse.SerializeToString,
            ),
            'PrepareUpdatePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareUpdatePrice,
                    request_deserializer=proto_dot_pos__service__pb2.PrepareUpdatePriceRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.PrepareUpdatePriceResponse.SerializeToString,
            ),
            'CommitUpdatePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitUpdatePrice,
                    request_deserializer=proto_dot_pos__service__pb2.CommitUpdatePriceRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.CommitUpdatePriceResponse.SerializeToString,
            ),
            'AbortUpdatePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortUpdatePrice,
                    request_deserializer=proto_dot_pos__service__pb2.AbortUpdatePriceRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.AbortUpdatePriceResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=proto_dot_pos__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_pos__service__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pos.POS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pos.POS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class POS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/GetProductPrice',
            proto_dot_pos__service__pb2.GetProductPriceRequest.SerializeToString,
            proto_dot_pos__service__pb2.GetProductPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProductPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/UpdateProductPrice',
            proto_dot_pos__service__pb2.UpdateProductPriceRequest.SerializeToString,
            proto_dot_pos__service__pb2.UpdateProductPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyPeersToUpdatePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/NotifyPeersToUpdatePrice',
            proto_dot_pos__service__pb2.UpdateProductPriceRequest.SerializeToString,
            proto_dot_pos__service__pb2.UpdateProductPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuyProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/BuyProduct',
            proto_dot_pos__service__pb2.BuyProductRequest.SerializeToString,
            proto_dot_pos__service__pb2.BuyProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/RequestStock',
            proto_dot_pos__service__pb2.RequestStockRequest.SerializeToString,
            proto_dot_pos__service__pb2.RequestStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareUpdatePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/PrepareUpdatePrice',
            proto_dot_pos__service__pb2.PrepareUpdatePriceRequest.SerializeToString,
            proto_dot_pos__service__pb2.PrepareUpdatePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitUpdatePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/CommitUpdatePrice',
            proto_dot_pos__service__pb2.CommitUpdatePriceRequest.SerializeToString,
            proto_dot_pos__service__pb2.CommitUpdatePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortUpdatePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/AbortUpdatePrice',
            proto_dot_pos__service__pb2.AbortUpdatePriceRequest.SerializeToString,
            proto_dot_pos__service__pb2.AbortUpdatePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pos.POS/SendHeartbeat',
            proto_dot_pos__service__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_pos__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
